### ISSUE TITLE
如果一个project里面有多个modules，查询的结果有点模糊。

### ISSUE THREAD

**Issue by Damon-Yo** [mrmanzhaow/RestfulToolkit#23]
我得project里面有多个modules，而且都是一样的代码，所以我查一个关键词的时候，出来的结果跟modules的数量是一样的，模糊的问题是，这些结果没有显示modules名，所以没办法知道哪条结果是那个modules里面的。不知道有没有解决办法。
搜索框里有一个是可以选择只显示当前modules的选项，但是也只是仅限于当前modules。

希望可以有办法解决这个情况吧。辛苦了

**Comment by aborn** [comment]
this fork dev has supported module search https://github.com/aborn/RestfulToolkit
