### ISSUE TITLE
能否增加对jar包中rest请求的扫描

### ISSUE THREAD

**Issue by GenweiWu** [mrmanzhaow/RestfulToolkit#3]
我现在使用了spinnaker项目，他的jar中就已经有很多rest请求了，但是现在貌似不支持搜索jar中的rest请求。这个能支持吗？

如果考虑性能问题，能否支持指定jar包。。。

**Comment by mrmanzhaow** [comment]
是的，现在不支持搜索非工程文件，初衷是为了方便定位文件方便编辑，功能不难实现，对性能多少会有影响的。当时考虑类似您这样的需求不多，所以把导航栏的Option选项实现为“Only this module ”，如果要实现就要把现在的 “Only this module ” 可选功能改为“Include non-project items” 了，我考虑一下。

目前，如果需要定位spinnaker 的rest请求实现，只能将spinnaker的源码引入工程了。

谢谢你的反馈。

**Comment by GenweiWu** [comment]
谢谢回复！
当前看，引入源码也是个办法。
不过这个插件真的很赞👍，加油
