### ISSUE TITLE
controller获取不全

### ISSUE THREAD

**Issue by longzl2015** [mrmanzhaow/RestfulToolkit#6]
在同一工程中，只能识别到部分的controller，有很大一部分的controller被漏掉了。

如下面的接口就没有被扫描到: 

![image](https://user-images.githubusercontent.com/12516505/46061283-b8895d80-c198-11e8-9771-b483143c9154.png)

**Comment by mrmanzhaow** [comment]
喔，是的，默认所有Controller都添加了 Controller、RestController 注解。

**Comment by occamrazor1492** [comment]
您使用什么方法来识别endpoint，以及endpoint里面的方法的呢

**Comment by longzl2015** [comment]
代替方案: 直接使用 IDEA 的console旁边的 Endpoints了。里面有 mappings信息，可以直接跳到对应方法了。

IntelliJ IDEA 2018.3.2

**Comment by mrmanzhaow** [comment]
endpoint 现在不支持，你这样自定义实现多么？

**Comment by finday3** [comment]
> endpoint 现在不支持，你这样自定义实现多么？


> endpoint 现在不支持，你这样自定义实现多么？

现在SpringCloud的项目都是这么写API了，这些接口都扫描不到
