### ISSUE TITLE
不同模块相同地址的显示问题

### ISSUE THREAD

**Issue by loong95** [mrmanzhaow/RestfulToolkit#7]
能不能添加一下不同模块的显示问题呢（加一下模块名称作为标识）？这样看不出来是哪个模块的接口

![image](https://user-images.githubusercontent.com/16333958/50327163-d9a7e300-0528-11e9-8c89-32a62cc4c18c.png)

**Comment by mrmanzhaow** [comment]
这个现在确实不支持，正常来说这种情况毕竟还是少数，添加了模块必然会占用一部分显示空间，所以暂时可能不会添加这个功能。遇到这种情况，可以勾选“Only This Module”，筛选出当前模块同名URL对应的Controller，如上的 “/attachement/downloadFile”。
